#include "mkpro/core/passes/helpers.hpp"

#include "test_support.hpp"

#include <string>

namespace mkpro::tests {

namespace {

using mkpro::core::passes::x2_structural_unary_debug;

void expect(int opcode, const std::string& fact, const std::string& expected) {
  const std::string actual = x2_structural_unary_debug(opcode, fact);
  require(actual == expected,
          "structural unary op=0x" + std::to_string(opcode) + " for [" + fact + "] expected\n  " +
              expected + "\ngot\n  " + actual);
}

}  // namespace

void x2_structural_unary_matches_typescript_contract() {
  expect(0x22, "hex:A:mantissa", "v=0|s=mantissa:00:decimal|dv=_|ds=_");
  expect(0x31, "hex:A:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:A:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:A:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:A:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:A:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:B:mantissa", "v=10|s=mantissa:10:decimal|dv=_|ds=_");
  expect(0x31, "hex:B:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:B:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:B:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:B:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:B:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:C:mantissa", "v=20|s=mantissa:20:decimal|dv=_|ds=_");
  expect(0x31, "hex:C:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:C:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:C:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:C:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:C:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:\xD0\xA1:mantissa", "v=20|s=mantissa:20:decimal|dv=_|ds=_");
  expect(0x31, "hex:\xD0\xA1:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:\xD0\xA1:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:\xD0\xA1:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:\xD0\xA1:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:\xD0\xA1:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:D:mantissa", "v=30|s=mantissa:30:decimal|dv=_|ds=_");
  expect(0x31, "hex:D:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:D:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:D:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:D:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:D:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:\xD0\x93:mantissa", "v=30|s=mantissa:30:decimal|dv=_|ds=_");
  expect(0x31, "hex:\xD0\x93:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:\xD0\x93:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:\xD0\x93:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:\xD0\x93:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:\xD0\x93:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:E:mantissa", "v=0|s=mantissa:0:decimal|dv=_|ds=_");
  expect(0x31, "hex:E:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:E:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:E:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:E:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:E:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:\xD0\x95:mantissa", "v=0|s=mantissa:0:decimal|dv=_|ds=_");
  expect(0x31, "hex:\xD0\x95:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:\xD0\x95:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:\xD0\x95:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:\xD0\x95:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:\xD0\x95:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:F:mantissa", "v=0|s=mantissa:0:decimal|dv=_|ds=_");
  expect(0x31, "hex:F:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:F:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x34, "hex:F:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:F:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:F:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:0A:mantissa", "v=0|s=mantissa:00:decimal|dv=_|ds=_");
  expect(0x31, "hex:0A:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:0A:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:0A:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:0A:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:0A:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:00B:mantissa", "v=10|s=mantissa:10:decimal|dv=_|ds=_");
  expect(0x31, "hex:00B:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:00B:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:00B:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:00B:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:00B:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:-A:mantissa", "v=0|s=mantissa:00:decimal|dv=_|ds=_");
  expect(0x31, "hex:-A:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:-A:mantissa", "v=-1|s=mantissa:-1:decimal|dv=_|ds=_");
  expect(0x34, "hex:-A:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:-A:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:-A:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:-\xD0\xA1:mantissa", "v=20|s=mantissa:20:decimal|dv=_|ds=_");
  expect(0x31, "hex:-\xD0\xA1:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:-\xD0\xA1:mantissa", "v=-1|s=mantissa:-1:decimal|dv=_|ds=_");
  expect(0x34, "hex:-\xD0\xA1:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:-\xD0\xA1:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:-\xD0\xA1:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:B0:mantissa", "v=1000|s=mantissa:1000:decimal|dv=_|ds=_");
  expect(0x31, "hex:B0:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:B0:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:B0:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:B0:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:B0:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:\xD0\xA1" "00:mantissa", "v=200000|s=mantissa:200000:decimal|dv=_|ds=_");
  expect(0x31, "hex:\xD0\xA1" "00:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:\xD0\xA1" "00:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:\xD0\xA1" "00:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:\xD0\xA1" "00:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:\xD0\xA1" "00:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:D000:mantissa", "v=30000000|s=mantissa:30000000:decimal|dv=_|ds=_");
  expect(0x31, "hex:D000:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:D000:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:D000:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:D000:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:D000:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:A0:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x31, "hex:A0:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:A0:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:A0:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:A0:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:A0:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:E0:mantissa", "v=0|s=mantissa:0:decimal|dv=_|ds=_");
  expect(0x31, "hex:E0:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:E0:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:E0:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:E0:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:E0:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:F00:mantissa", "v=0|s=mantissa:0:decimal|dv=_|ds=_");
  expect(0x31, "hex:F00:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:F00:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x34, "hex:F00:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:F00:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:F00:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:A00:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x31, "hex:A00:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:A00:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:A00:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:A00:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:A00:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:0.C:mantissa", "v=0.2|s=exponent:2:-1:decimal|dv=_|ds=_");
  expect(0x31, "hex:0.C:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:0.C:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:0.C:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:0.C:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:0.C:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:.A:mantissa", "v=0|s=exponent:0:-1:decimal|dv=_|ds=_");
  expect(0x31, "hex:.A:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:.A:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:.A:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:.A:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:.A:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:0.0B:mantissa", "v=0.001|s=exponent:1:-3:decimal|dv=_|ds=_");
  expect(0x31, "hex:0.0B:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:0.0B:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:0.0B:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:0.0B:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:0.0B:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:0.00\xD0\x95:mantissa", "v=0|s=mantissa:0:decimal|dv=_|ds=_");
  expect(0x31, "hex:0.00\xD0\x95:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:0.00\xD0\x95:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:0.00\xD0\x95:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:0.00\xD0\x95:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:0.00\xD0\x95:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:10:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x31, "hex:10:mantissa", "v=10|s=mantissa:10:decimal|dv=_|ds=_");
  expect(0x32, "hex:10:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:10:mantissa", "v=10|s=mantissa:10:decimal|dv=_|ds=_");
  expect(0x35, "hex:10:mantissa", "v=0|s=mantissa:0:decimal|dv=_|ds=_");
  expect(0x3a, "hex:10:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:5:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x31, "hex:5:mantissa", "v=5|s=mantissa:5:decimal|dv=_|ds=_");
  expect(0x32, "hex:5:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:5:mantissa", "v=5|s=mantissa:5:decimal|dv=_|ds=_");
  expect(0x35, "hex:5:mantissa", "v=0|s=mantissa:0:decimal|dv=_|ds=_");
  expect(0x3a, "hex:5:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:12345678:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x31, "hex:12345678:mantissa", "v=12345678|s=mantissa:12345678:decimal|dv=_|ds=_");
  expect(0x32, "hex:12345678:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:12345678:mantissa", "v=12345678|s=mantissa:12345678:decimal|dv=_|ds=_");
  expect(0x35, "hex:12345678:mantissa", "v=0|s=mantissa:0:decimal|dv=_|ds=_");
  expect(0x3a, "hex:12345678:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex:F.FFFFFFF:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x31, "hex:F.FFFFFFF:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex:F.FFFFFFF:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x34, "hex:F.FFFFFFF:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex:F.FFFFFFF:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex:F.FFFFFFF:mantissa", "v=8|s=mantissa:8.0000000:decimal|dv=_|ds=_");
  expect(0x22, "hex:1.2345678:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x31, "hex:1.2345678:mantissa", "v=1.2345678|s=mantissa:1.2345678:decimal|dv=_|ds=_");
  expect(0x32, "hex:1.2345678:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex:1.2345678:mantissa", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x35, "hex:1.2345678:mantissa", "v=0.2345678|s=exponent:2.345678:-1:decimal|dv=_|ds=_");
  expect(0x3a, "hex:1.2345678:mantissa", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex-exponent:A:1", "v=0|s=mantissa:0000:decimal|dv=_|ds=_");
  expect(0x31, "hex-exponent:A:1", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex-exponent:A:1", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex-exponent:A:1", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex-exponent:A:1", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex-exponent:A:1", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex-exponent:B:-2", "v=0.001|s=exponent:1:-3:decimal|dv=_|ds=_");
  expect(0x31, "hex-exponent:B:-2", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex-exponent:B:-2", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex-exponent:B:-2", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex-exponent:B:-2", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex-exponent:B:-2", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex-exponent:0.C:3", "v=200000|s=mantissa:200000:decimal|dv=_|ds=_");
  expect(0x31, "hex-exponent:0.C:3", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex-exponent:0.C:3", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex-exponent:0.C:3", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex-exponent:0.C:3", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex-exponent:0.C:3", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex-exponent:\xD0\xA1:2", "v=200000|s=mantissa:200000:decimal|dv=_|ds=_");
  expect(0x31, "hex-exponent:\xD0\xA1:2", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex-exponent:\xD0\xA1:2", "v=1|s=mantissa:1:decimal|dv=_|ds=_");
  expect(0x34, "hex-exponent:\xD0\xA1:2", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex-exponent:\xD0\xA1:2", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex-exponent:\xD0\xA1:2", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "hex-exponent:F:-1", "v=0|s=mantissa:0:decimal|dv=_|ds=_");
  expect(0x31, "hex-exponent:F:-1", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "hex-exponent:F:-1", "v=_|s=_|dv=_|ds=_");
  expect(0x34, "hex-exponent:F:-1", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "hex-exponent:F:-1", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "hex-exponent:F:-1", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "super:FA", "v=0|s=mantissa:0:decimal|dv=_|ds=_");
  expect(0x31, "super:FA", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "super:FA", "v=0|s=mantissa:0:decimal|dv=_|ds=_");
  expect(0x34, "super:FA", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "super:FA", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "super:FA", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "super:FB", "v=0|s=mantissa:0:decimal|dv=_|ds=_");
  expect(0x31, "super:FB", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "super:FB", "v=0|s=mantissa:0:decimal|dv=_|ds=_");
  expect(0x34, "super:FB", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "super:FB", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "super:FB", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "super-exponent:FA:0", "v=0|s=mantissa:0:decimal|dv=_|ds=_");
  expect(0x31, "super-exponent:FA:0", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "super-exponent:FA:0", "v=0|s=mantissa:0:decimal|dv=0|ds=mantissa:0:decimal");
  expect(0x34, "super-exponent:FA:0", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "super-exponent:FA:0", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "super-exponent:FA:0", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "super-exponent:FA:-1", "v=_|s=_|dv=_|ds=_");
  expect(0x31, "super-exponent:FA:-1", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "super-exponent:FA:-1", "v=_|s=_|dv=_|ds=_");
  expect(0x34, "super-exponent:FA:-1", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "super-exponent:FA:-1", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "super-exponent:FA:-1", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "super-exponent:FB:2", "v=_|s=_|dv=_|ds=_");
  expect(0x31, "super-exponent:FB:2", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "super-exponent:FB:2", "v=_|s=_|dv=0|ds=mantissa:0:decimal");
  expect(0x34, "super-exponent:FB:2", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "super-exponent:FB:2", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "super-exponent:FB:2", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "mantissa:5:decimal", "v=_|s=_|dv=_|ds=_");
  expect(0x31, "mantissa:5:decimal", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "mantissa:5:decimal", "v=_|s=_|dv=_|ds=_");
  expect(0x34, "mantissa:5:decimal", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "mantissa:5:decimal", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "mantissa:5:decimal", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "mantissa:1.5:decimal", "v=_|s=_|dv=_|ds=_");
  expect(0x31, "mantissa:1.5:decimal", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "mantissa:1.5:decimal", "v=_|s=_|dv=_|ds=_");
  expect(0x34, "mantissa:1.5:decimal", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "mantissa:1.5:decimal", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "mantissa:1.5:decimal", "v=_|s=_|dv=_|ds=_");
  expect(0x22, "exponent:1:5:decimal", "v=_|s=_|dv=_|ds=_");
  expect(0x31, "exponent:1:5:decimal", "v=_|s=_|dv=_|ds=_");
  expect(0x32, "exponent:1:5:decimal", "v=_|s=_|dv=_|ds=_");
  expect(0x34, "exponent:1:5:decimal", "v=_|s=_|dv=_|ds=_");
  expect(0x35, "exponent:1:5:decimal", "v=_|s=_|dv=_|ds=_");
  expect(0x3a, "exponent:1:5:decimal", "v=_|s=_|dv=_|ds=_");
}

}  // namespace mkpro::tests
