import type { EmitContext } from "../compiler.ts";

/**
 * Narrow contract that the lowering domain modules (emit/lowering/*) operate
 * against. It is the exact public surface of EmitContext that the relocated
 * free functions consume — derived via Pick so signatures stay in sync, while
 * preventing the domains from reaching into any other EmitContext member.
 * EmitContext satisfies this contract structurally (checked wherever `this` is
 * passed into a lowering function), so no explicit `implements` is required.
 */
export type LoweringCtx = Pick<
  EmitContext,
  | "allocation"
  | "ast"
  | "branchOrderStatement"
  | "canReorderNumericDisplay"
  | "candidates"
  | "collapseLiteralOnlyDisplay"
  | "collapseTextPrefixDisplay"
  | "compileStatements"
  | "compileWithinProcedure"
  | "constantStack"
  | "constants"
  | "coordListCounterKnownOne"
  | "coordListFusedHitBodyAllowed"
  | "coordListIndirectContext"
  | "coordListLineCountAssignmentFromStatement"
  | "coordListUsesScaledDecimalStorage"
  | "currentAddress"
  | "currentXAliases"
  | "currentXDashedCoordReportBody"
  | "currentXDashedCoordReportBodyMatches"
  | "currentXKnownZero"
  | "currentXVariable"
  | "dashedCoordReportTemplateAfterLineCount"
  | "diagnostics"
  | "directTerminalCallTarget"
  | "displayByteHelpers"
  | "displayFieldCanBeZero"
  | "displayFieldFitsUnsignedWidth"
  | "displayHelpers"
  | "displayMaskRegister"
  | "displayMaskScratchRegister"
  | "displayTemplateScratchRegisters"
  | "emitAddress"
  | "emitFormalAddress"
  | "emitJump"
  | "emitLabel"
  | "emitIndexedRecall"
  | "emitIndexedStore"
  | "emitNumber"
  | "emitNumberOrPreload"
  | "emitOp"
  | "emitRecall"
  | "emitStore"
  | "emitZero"
  | "emittingExpressionHelper"
  | "emittingRandomCellHelper"
  | "ensureSpatialBitMaskHelper"
  | "ensureSpatialHitHelper"
  | "ensureSpatialLineProgressionHelper"
  | "ensureSpatialSumLoopHelper"
  | "ensureTerminalTailHelper"
  | "ensureLine4MoveHelper"
  | "estimateNumberOrPreloadCost"
  | "expressionHelpers"
  | "falseBranchCurrentXCandidate"
  | "findStateField"
  | "firstSpliceDisplayScratch"
  | "freshLabel"
  | "functionProcs"
  | "inlineProcNames"
  | "items"
  | "lineCountCallCount"
  | "lineCountHelpers"
  | "line4MoveHelpers"
  | "literalDisplayHelpers"
  | "loweringOptions"
  | "machineEntryOpen"
  | "machineProfile"
  | "mantissaExponentDisplayTemplate"
  | "mantissaMaskDisplayTemplate"
  | "membershipClearPrefix"
  | "membershipSetPrefix"
  | "membershipSetRunPrefix"
  | "nearAnyFallthroughCandidate"
  | "nearAnyHelper"
  | "nearAnyHelperStats"
  | "nearAnyHelpers"
  | "numericDisplayFields"
  | "optimizations"
  | "orderStorageReuseFields"
  | "packedStorageReuseFields"
  | "procCallCounts"
  | "procReturnXVariable"
  | "randomCellHelpers"
  | "randomCoordListSetupContext"
  | "readCounts"
  | "recordRejectedNegativeZeroBranchCandidate"
  | "reportPackedDisplayLowering"
  | "scaleCoordListCellInPlace"
  | "scaledCoordVariables"
  | "removableCoordLists"
  | "scratchRegistersAvailable"
  | "selectDisplayStrategy"
  | "sharedBitMaskHelperScratch"
  | "sharedDisplayByteHelper"
  | "sharedDisplayHelper"
  | "sharedExpressionHelper"
  | "sharedLineCountHelper"
  | "sharedLiteralDisplayHelper"
  | "sharedRandomCellHelper"
  | "sharedShowSequenceHelper"
  | "showSequenceHelpers"
  | "snapshotBankSelectorCache"
  | "signDigitLiteralScratch"
  | "spatialBitMaskHelpers"
  | "spatialHitHelpers"
  | "spatialLineProgressionHelpers"
  | "spatialSumLoopHelpers"
  | "statementsTerminate"
  | "terminalTailHelpers"
  | "variableDisplayMaskRegisters"
  | "variableLeadingMantissaMaskDisplayTemplate"
  | "restoreBankSelectorCacheAfterCall"
  | "xHolds"
  | "xParamProcs"
  | "zeroAddressLabels"
>;
